#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 *
 * Created from SOPC Builder system 'SoC_Shamir' in
 * file './SoC_Shamir.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 *
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'Shamire_core_0', class 'Shamire_core'
 * The macros are prefixed with 'SHAMIRE_CORE_0_'.
 * The prefix is the slave descriptor.
 */
#define SHAMIRE_CORE_0_COMPONENT_TYPE Shamire_core
#define SHAMIRE_CORE_0_COMPONENT_NAME Shamire_core_0
#define SHAMIRE_CORE_0_BASE 0x0
#define SHAMIRE_CORE_0_SPAN 256
#define SHAMIRE_CORE_0_END 0xff

#endif /* _ALTERA_HPS_0_H_ */
